### ISSUE TITLE
Impossible d'ajouter des questions

### ISSUE THREAD

**Issue by e-riff** [WildCodeSchool/2022-09-php-remote-p2-super-quizz#41]
Problème d'ajout des questions : 
**Avec fichiers :** 
Erreur non gérée si fichier trop gros (gnix --> Probleme du serveur de deploy ?)
Erreur manager si fichier accepté (idem que pour les autres chargements d'image)
**Sans fichier :** 
Accepte mais ne l'ajoute pas

**Comment by Florent-V** [comment]
t'as vérifié le filtre du thème en haut ? Comme il y a 3000 questions il y a automatiquement un filtre placé sur culture générale, essaie de remettre le filtre correspond au thème dont tu as ajouté la question.
