### ISSUE TITLE
Catégorie humour

### ISSUE THREAD

**Issue by jeanfrancois-morin** [WildCodeSchool/2022-09-php-remote-p2-super-quizz#45]
J'ai eu cette erreur lors d'un jeu dans la catégorie Humour  :`Undefined array key 6`
Au bout de 5 questions ~

**Comment by Florent-V** [comment]
Chez beta-testeur,
Dans le readme, il y a une partie "know issues" facilement accessible via un lien dans la table des manières qui indique que ce bug est connu.
Notre formateur nous avait pourtant indiqué qu'il fallait regarder cette partie en premier. ;-)
N'ayez crainte notre équipe d'auteur bosse d'arrache pied pour écrire des questions dans ce thème qui vous tient tant à cœur ! :-D
